/**
 * Partner Logos Data
 * Auto-generated by process-partner-logos.mjs
 * Updated: 2026-01-14 (Client verification corrections)
 */

export interface Partner {
  id: string;
  name: string;
  category: string;
  logo: string;
}

export const partners: Partner[] = [
  {
    id: 'ciments-du-maroc',
    name: 'Ciments du Maroc',
    category: 'Matériaux de construction',
    logo: '/images/real/partners-processed/ciments-du-maroc.png'
  },
  {
    id: 'sonasid',
    name: 'Sonasid',
    category: 'Acier et métallurgie',
    logo: '/images/real/partners-processed/sonasid.png'
  },
  {
    id: 'gadimat',
    name: 'Gadimat',
    category: 'Bois et panneaux',
    logo: '/images/real/partners-processed/gadimat.png'
  },
  {
    id: 'ariston',
    name: 'Ariston',
    category: 'Chauffage et eau chaude',
    logo: '/images/real/partners-processed/ariston.png'
  },
  {
    id: 'etaf',
    name: 'ETAF',
    category: 'Équipement produit métallurgie',
    logo: '/images/real/partners-processed/etaf.png'
  },
  {
    id: 'nova-gnd',
    name: 'Nova GND',
    category: 'Sanitaire et robinetterie',
    logo: '/images/real/partners-processed/nova-gnd.png'
  },
  {
    id: 'socodam-davum',
    name: 'Socodam Davum',
    category: 'Acier et métallurgie',
    logo: '/images/real/partners-processed/socodam-davum.png'
  },
  {
    id: 'cifre-ceramica',
    name: 'Cifre Ceramica',
    category: 'Carrelage et céramique',
    logo: '/images/real/partners-processed/cifre-ceramica.png'
  },
  {
    id: 'ingelec',
    name: 'Ingelec',
    category: 'Électricité',
    logo: '/images/real/partners-processed/ingelec.png'
  },
  {
    id: 'sika',
    name: 'Sika',
    category: 'Chimie du bâtiment',
    logo: '/images/real/partners-processed/sika.png'
  },
  {
    id: 'atlas-peintures',
    name: 'Atlas Peintures',
    category: 'Peintures et revêtements',
    logo: '/images/real/partners-processed/atlas-peintures.png'
  },
  {
    id: 'kadir-distribution',
    name: 'Kadir Distribution',
    category: 'Distribution sanitaire et plomberie',
    logo: '/images/real/partners-processed/kadir-distribution.png'
  },
  {
    id: 'sofa',
    name: 'SOFA',
    category: 'Électricité',
    logo: '/images/real/partners-processed/sofa.png'
  },
  {
    id: 'lap',
    name: 'LAP',
    category: 'Matériel électrique',
    logo: '/images/real/partners-processed/lap.png'
  },
  {
    id: 'vitra',
    name: 'VitrA',
    category: 'Sanitaire et céramique',
    logo: '/images/real/partners-processed/vitra.png'
  },
  // New partners added from client verification (2026-01-14)
  {
    id: 'icat-international',
    name: 'ICAT International',
    category: 'Ventilation, Climatisation, Filtration',
    logo: '/images/real/partners-processed/icat-international.png'
  },
  {
    id: 'bitulife',
    name: 'BITULIFE',
    category: 'Étanchéité',
    logo: '/images/real/partners-processed/bitulife.png'
  },
  {
    id: 'milwaukee',
    name: 'MILWAUKEE',
    category: 'Outillage',
    logo: '/images/real/partners-processed/milwaukee.png'
  }
];

export const partnerCategories = [
  'Matériaux de construction',
  'Acier et métallurgie',
  'Bois et panneaux',
  'Chauffage et eau chaude',
  'Électricité',
  'Carrelage et céramique',
  'Chimie du bâtiment',
  'Peintures et revêtements',
  'Distribution sanitaire et plomberie',
  'Matériel électrique',
  'Sanitaire et céramique',
  'Sanitaire et robinetterie',
  'Équipement produit métallurgie',
  'Ventilation, Climatisation, Filtration',
  'Étanchéité',
  'Outillage'
] as const;

export type PartnerCategory = typeof partnerCategories[number];

export default partners;

