/**
 * Partner Logos Data
 * Auto-generated by process-partner-logos.mjs
 * Generated on: 2026-01-12T14:53:56.191Z
 */

export interface Partner {
  id: string;
  name: string;
  category: string;
  logo: string;
}

export const partners: Partner[] = [
  {
    id: 'ciments-du-maroc',
    name: 'Ciments du Maroc',
    category: 'Matériaux de construction',
    logo: '/images/real/partners-processed/ciments-du-maroc.png'
  },
  {
    id: 'sonasid',
    name: 'Sonasid',
    category: 'Acier et métallurgie',
    logo: '/images/real/partners-processed/sonasid.png'
  },
  {
    id: 'gadimat',
    name: 'Gadimat',
    category: 'Bois et panneaux',
    logo: '/images/real/partners-processed/gadimat.png'
  },
  {
    id: 'ariston',
    name: 'Ariston',
    category: 'Chauffage et eau chaude',
    logo: '/images/real/partners-processed/ariston.png'
  },
  {
    id: 'etaf',
    name: 'ETAF',
    category: 'Équipement',
    logo: '/images/real/partners-processed/etaf.png'
  },
  {
    id: 'nova-gnd',
    name: 'Nova GND',
    category: 'Équipement',
    logo: '/images/real/partners-processed/nova-gnd.png'
  },
  {
    id: 'socodam-davum',
    name: 'Socodam Davum',
    category: 'Distribution',
    logo: '/images/real/partners-processed/socodam-davum.png'
  },
  {
    id: 'cifre-ceramica',
    name: 'Cifre Ceramica',
    category: 'Carrelage et céramique',
    logo: '/images/real/partners-processed/cifre-ceramica.png'
  },
  {
    id: 'ingelec',
    name: 'Ingelec',
    category: 'Électricité',
    logo: '/images/real/partners-processed/ingelec.png'
  },
  {
    id: 'sika',
    name: 'Sika',
    category: 'Chimie du bâtiment',
    logo: '/images/real/partners-processed/sika.png'
  },
  {
    id: 'atlas-peintures',
    name: 'Atlas Peintures',
    category: 'Peintures et revêtements',
    logo: '/images/real/partners-processed/atlas-peintures.png'
  },
  {
    id: 'kadir-distribution',
    name: 'Kadir Distribution',
    category: 'Distribution sanitaire',
    logo: '/images/real/partners-processed/kadir-distribution.png'
  },
  {
    id: 'sofa',
    name: 'SOFA',
    category: 'Matériel électrique',
    logo: '/images/real/partners-processed/sofa.png'
  },
  {
    id: 'olap',
    name: 'OLAP',
    category: 'Électricité',
    logo: '/images/real/partners-processed/olap.png'
  },
  {
    id: 'vitra',
    name: 'VitrA',
    category: 'Sanitaire et céramique',
    logo: '/images/real/partners-processed/vitra.png'
  }
];

export const partnerCategories = [
  'Matériaux de construction',
  'Acier et métallurgie',
  'Bois et panneaux',
  'Chauffage et eau chaude',
  'Électricité',
  'Distribution',
  'Carrelage et céramique',
  'Chimie du bâtiment',
  'Peintures et revêtements',
  'Distribution sanitaire',
  'Matériel électrique',
  'Sanitaire et céramique',
  'Équipement'
] as const;

export type PartnerCategory = typeof partnerCategories[number];

export default partners;
